<?php

  require_once ('inc/class-security.php');

  /**
   * Displaing an application random token generated by specific class methods
   */
  function get_random_token(){
    $security = new Security;
    $randomToken = $security->createRandomToken();
    echo $randomToken;
  }

  get_random_token();

?>
